version: 0.0
os: linux
files:
  - source: /
    destination: /webapp/
permissions:
  - object: /
    pattern: "**"
    owner: root
    group: root

hooks:
  BeforeInstall:
    - location: start.sh
      timeout: 30
      runas: root
  ApplicationStart:
    - location: applicationStart.sh
      timeout: 300
      runas: root